// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package api

import (
	"time"
)

// ErrInfo defines model for ErrInfo.
type ErrInfo struct {
	Description string `json:"description"`
	Err         int    `json:"err"`
}

// ImportantInfo defines model for ImportantInfo.
type ImportantInfo struct {
	Avatar    string    `json:"avatar"`
	Bio       string    `json:"bio"`
	CreatedAt time.Time `json:"created_at"`
	Images    []Media   `json:"images"`
	Name      string    `json:"name"`
	Username  string    `json:"username"`
	Videos    []Media   `json:"videos"`
}

// Inside defines model for Inside.
type Inside struct {
	Id string `json:"id"`
}

// Media defines model for Media.
type Media struct {
	Description string `json:"description"`
	Url         string `json:"url"`
}

// OutputData defines model for OutputData.
type OutputData struct {
	Error  *ErrInfo      `json:"error,omitempty"`
	Output ImportantInfo `json:"output"`
	State  string        `json:"state"`
}

// User defines model for User.
type User struct {
	Username string `json:"username"`
}

// PostUsersJSONBody defines parameters for PostUsers.
type PostUsersJSONBody User

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody PostUsersJSONBody
